# Generated by Django 3.1.7 on 2021-03-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecl.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='ALL', max_length=20),
        ),
    ]
